# hosts.inventory
# ---
# the host and group list for this example "Ansibled" project

#[elasticsearch]
#big.elasticsearch.ansibled
#small.elasticsearch.ansibled
#[aurora.cluster]
#cluster.aurora.ansibled
#[aurora.db]
#dba.aurora.ansibled
#dbb.aurora.ansibled

[vpc]
vpc.ansibled

#[project.ansibled:children]
[project_ansibled:children]
vpc
#aurora.cluster
#aurora.db
#elasticsearch
